// flow-typed signature: e802b486e9a5bc3653461d6d5d0688e1
// flow-typed version: <<STUB>>/markdown-to-jsx_v^6.6.9/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-to-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-to-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-to-jsx/dist/cjs' {
  declare module.exports: any;
}

declare module 'markdown-to-jsx/dist/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-to-jsx/dist/cjs.js' {
  declare module.exports: $Exports<'markdown-to-jsx/dist/cjs'>;
}
declare module 'markdown-to-jsx/dist/esm.js' {
  declare module.exports: $Exports<'markdown-to-jsx/dist/esm'>;
}
declare module 'markdown-to-jsx/index' {
  declare module.exports: $Exports<'markdown-to-jsx'>;
}
declare module 'markdown-to-jsx/index.js' {
  declare module.exports: $Exports<'markdown-to-jsx'>;
}
