// flow-typed signature: cccb8942f4b1c51f732704e476e65d86
// flow-typed version: <<STUB>>/react-loader-spinner_v^2.1.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loader-spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loader-spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loader-spinner/dist/index' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/audio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/ball-triangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/bars' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/circles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/grid' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/hearts' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/oval' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/puff' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/rings' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/tail-spin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loading/three-dots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/scripts/mocha_runner' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/index' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/audio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/ball-triangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/bars' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/circles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/grid' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/hearts' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/oval' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/puff' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/rings' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/tail-spin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/src/loading/three-dots' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loader-spinner/dist/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/index'>;
}
declare module 'react-loader-spinner/dist/loading/audio.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/audio'>;
}
declare module 'react-loader-spinner/dist/loading/ball-triangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/ball-triangle'>;
}
declare module 'react-loader-spinner/dist/loading/bars.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/bars'>;
}
declare module 'react-loader-spinner/dist/loading/circles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/circles'>;
}
declare module 'react-loader-spinner/dist/loading/grid.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/grid'>;
}
declare module 'react-loader-spinner/dist/loading/hearts.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/hearts'>;
}
declare module 'react-loader-spinner/dist/loading/oval.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/oval'>;
}
declare module 'react-loader-spinner/dist/loading/puff.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/puff'>;
}
declare module 'react-loader-spinner/dist/loading/rings.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/rings'>;
}
declare module 'react-loader-spinner/dist/loading/tail-spin.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/tail-spin'>;
}
declare module 'react-loader-spinner/dist/loading/three-dots.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loading/three-dots'>;
}
declare module 'react-loader-spinner/index' {
  declare module.exports: $Exports<'react-loader-spinner'>;
}
declare module 'react-loader-spinner/index.js' {
  declare module.exports: $Exports<'react-loader-spinner'>;
}
declare module 'react-loader-spinner/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'react-loader-spinner/scripts/mocha_runner'>;
}
declare module 'react-loader-spinner/src/__tests__/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/__tests__/index'>;
}
declare module 'react-loader-spinner/src/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/index'>;
}
declare module 'react-loader-spinner/src/loading/audio.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/audio'>;
}
declare module 'react-loader-spinner/src/loading/ball-triangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/ball-triangle'>;
}
declare module 'react-loader-spinner/src/loading/bars.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/bars'>;
}
declare module 'react-loader-spinner/src/loading/circles.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/circles'>;
}
declare module 'react-loader-spinner/src/loading/grid.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/grid'>;
}
declare module 'react-loader-spinner/src/loading/hearts.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/hearts'>;
}
declare module 'react-loader-spinner/src/loading/oval.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/oval'>;
}
declare module 'react-loader-spinner/src/loading/puff.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/puff'>;
}
declare module 'react-loader-spinner/src/loading/rings.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/rings'>;
}
declare module 'react-loader-spinner/src/loading/tail-spin.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/tail-spin'>;
}
declare module 'react-loader-spinner/src/loading/three-dots.js' {
  declare module.exports: $Exports<'react-loader-spinner/src/loading/three-dots'>;
}
