// flow-typed signature: 70c3ca467a6b28c791e3f2bd3ee1a68c
// flow-typed version: <<STUB>>/react-lazy-hero_v^0.4.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lazy-hero'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lazy-hero' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-lazy-hero/lib/index' {
  declare module.exports: any;
}

declare module 'react-lazy-hero/lib/LazyHero' {
  declare module.exports: any;
}

declare module 'react-lazy-hero/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-lazy-hero/lib/index.js' {
  declare module.exports: $Exports<'react-lazy-hero/lib/index'>;
}
declare module 'react-lazy-hero/lib/LazyHero.js' {
  declare module.exports: $Exports<'react-lazy-hero/lib/LazyHero'>;
}
declare module 'react-lazy-hero/lib/utils.js' {
  declare module.exports: $Exports<'react-lazy-hero/lib/utils'>;
}
