// flow-typed signature: b149bdba72b29a20b2f4d646a91ac53f
// flow-typed version: <<STUB>>/react-typed_v^1.1.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-typed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-typed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-typed/__tests__/react-typed.test' {
  declare module.exports: any;
}

declare module 'react-typed/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-typed/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-typed/dist/react-typed' {
  declare module.exports: any;
}

declare module 'react-typed/dist/react-typed.min' {
  declare module.exports: any;
}

declare module 'react-typed/stories/index' {
  declare module.exports: any;
}

declare module 'react-typed/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-typed/__tests__/react-typed.test.js' {
  declare module.exports: $Exports<'react-typed/__tests__/react-typed.test'>;
}
declare module 'react-typed/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-typed/coverage/lcov-report/prettify'>;
}
declare module 'react-typed/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-typed/coverage/lcov-report/sorter'>;
}
declare module 'react-typed/dist/react-typed.js' {
  declare module.exports: $Exports<'react-typed/dist/react-typed'>;
}
declare module 'react-typed/dist/react-typed.min.js' {
  declare module.exports: $Exports<'react-typed/dist/react-typed.min'>;
}
declare module 'react-typed/stories/index.js' {
  declare module.exports: $Exports<'react-typed/stories/index'>;
}
declare module 'react-typed/webpack.config.js' {
  declare module.exports: $Exports<'react-typed/webpack.config'>;
}
