// flow-typed signature: b77f36e26316c482a18dad91be2bb03d
// flow-typed version: <<STUB>>/react-markdown-plus_v^0.1.1-a/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown-plus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-markdown-plus/exam/App' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/exam/index' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/exam/webpack.config' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/lib/Markdown' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/lib/render/index' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/lib/render/katex' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/lib/render/prism' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/src/Markdown' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/src/render/index' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/src/render/katex' {
  declare module.exports: any;
}

declare module 'react-markdown-plus/src/render/prism' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-markdown-plus/exam/App.js' {
  declare module.exports: $Exports<'react-markdown-plus/exam/App'>;
}
declare module 'react-markdown-plus/exam/index.js' {
  declare module.exports: $Exports<'react-markdown-plus/exam/index'>;
}
declare module 'react-markdown-plus/exam/webpack.config.js' {
  declare module.exports: $Exports<'react-markdown-plus/exam/webpack.config'>;
}
declare module 'react-markdown-plus/index' {
  declare module.exports: $Exports<'react-markdown-plus'>;
}
declare module 'react-markdown-plus/index.js' {
  declare module.exports: $Exports<'react-markdown-plus'>;
}
declare module 'react-markdown-plus/lib/Markdown.js' {
  declare module.exports: $Exports<'react-markdown-plus/lib/Markdown'>;
}
declare module 'react-markdown-plus/lib/render/index.js' {
  declare module.exports: $Exports<'react-markdown-plus/lib/render/index'>;
}
declare module 'react-markdown-plus/lib/render/katex.js' {
  declare module.exports: $Exports<'react-markdown-plus/lib/render/katex'>;
}
declare module 'react-markdown-plus/lib/render/prism.js' {
  declare module.exports: $Exports<'react-markdown-plus/lib/render/prism'>;
}
declare module 'react-markdown-plus/src/Markdown.js' {
  declare module.exports: $Exports<'react-markdown-plus/src/Markdown'>;
}
declare module 'react-markdown-plus/src/render/index.js' {
  declare module.exports: $Exports<'react-markdown-plus/src/render/index'>;
}
declare module 'react-markdown-plus/src/render/katex.js' {
  declare module.exports: $Exports<'react-markdown-plus/src/render/katex'>;
}
declare module 'react-markdown-plus/src/render/prism.js' {
  declare module.exports: $Exports<'react-markdown-plus/src/render/prism'>;
}
