// flow-typed signature: e49ffcdc620ecc4552e001fea9d6569c
// flow-typed version: <<STUB>>/react-messenger-customer-chat_v^0.7.2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-messenger-customer-chat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-messenger-customer-chat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-messenger-customer-chat/lib/index' {
  declare module.exports: any;
}

declare module 'react-messenger-customer-chat/lib/MessengerCustomerChat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-messenger-customer-chat/lib/index.js' {
  declare module.exports: $Exports<'react-messenger-customer-chat/lib/index'>;
}
declare module 'react-messenger-customer-chat/lib/MessengerCustomerChat.js' {
  declare module.exports: $Exports<'react-messenger-customer-chat/lib/MessengerCustomerChat'>;
}
