// flow-typed signature: 6714a2d8d83302d54956eb0b80d135ee
// flow-typed version: <<STUB>>/@types/node_v^10.12.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
