// flow-typed signature: d19e616c88ad7ab154ffaf215d3df1d9
// flow-typed version: <<STUB>>/@types/react-dom_v^16.0.9/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
